describe('Stan\'s Spec', () => {
    // it('logs in', () => {
    //     cy.visit('/')
    //       .get('input[name="email"]')
    //       .type(Cypress.env("email"))
    //       .get('input[name="password"]')
    //       .type(Cypress.env("password"))
    //       .get('button')
    //       .click()
    //       .url()
    //       .should('include', '/admin/organisation')
    // })

    it('changes admin password from the menu', () => {
        cy.visit('/')
          .get('input[name="email"]').type('stasoletesting+Around@gmail.com') //can we store username and password in env variable which is stored in cypress.json file 
          .get('input[name="password"]').type('letitsnow1')
          .get('button').click()
          .get('#__BVID__15__BV_toggle_').click()
          .get('a').contains('Reset Password').click()
          .get('#input-58').type('letitsnow1')
          .get('#input-63').type('letitsnow1')
          .get('span').contains('submit').click()
          .get('#__BVID__15__BV_toggle_').click()
          .get('button').contains('Logout').click()
          .get('input[name="email"]').type('stasoletesting+Around@gmail.com')
          .get('input[name="password"]').type('letitsnow1')
          .get('button').click()
          .url().should('include', '/admin/preview')
    })
})